name: '빌드 및 설정 작업'
description: '빌드 시스템, 설정, 의존성 관리 등에 대한 이슈입니다.'
title: 'chore: '
labels: ['chore']
body:
  - type: textarea
    attributes:
      label: ⚙️ 작업 개요
      description: 수행할 chore 작업에 대한 설명을 작성해 주세요.
      placeholder: |
        어떤 종류의 작업을 수행할 예정인가요?
        예) 의존성 업데이트, 빌드 설정 개선, CI/CD 파이프라인 수정 등
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 🛠️ 작업 유형
      description: 수행할 작업의 유형을 선택해 주세요.
      options:
        - 의존성 업데이트
        - 빌드 시스템 개선
        - CI/CD 파이프라인
        - 개발 환경 설정
        - 코드 포맷팅/린팅
        - 패키지 설정
        - 배포 설정
        - 기타
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업 내용
      description: 구체적인 작업 내용을 체크리스트로 작성해 주세요.
      placeholder: |
        - [ ] 패키지 의존성 업데이트
        - [ ] 빌드 스크립트 개선
        - [ ] ESLint 규칙 추가
        - [ ] GitHub Actions 워크플로우 수정
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🎯 기대 효과
      description: 이 작업을 통해 기대하는 개선 효과를 작성해 주세요.
      placeholder: |
        - 빌드 시간 단축
        - 개발 경험 개선
        - 코드 품질 향상
        - 보안 취약점 해결
    validations:
      required: false
  - type: textarea
    attributes:
      label: ⚠️ 주의사항
      description: 작업 시 주의해야 할 사항이나 영향도를 작성해 주세요.
      placeholder: |
        - Breaking changes 여부
        - 다른 팀원들에게 미치는 영향
        - 마이그레이션 가이드 필요 여부
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🏄‍♂️ 참고 자료
      description: 작업에 참고할 자료가 있다면 작성해 주세요.
      placeholder: |
        - 공식 마이그레이션 가이드
        - 관련 이슈/PR 링크
        - 참고한 다른 프로젝트
    validations:
      required: false